import javax.swing.*;
import java.awt.*;

public class Border {
    private JPanel panel1;
    private JButton button1;


    private void createUIComponents() {
        // TODO: place custom component creation code here
        panel1 = new JPanel();


    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        createUIComponents();
        panel1.setLayout(new BorderLayout(0, 0));
        panel1.setInheritsPopupMenu(false);
        panel1.setMinimumSize(new Dimension(600, 600));
        button1 = new JButton();
        button1.setText("Button");
        panel1.add(button1, BorderLayout.SOUTH);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return panel1;
    }
}
